


CREATE DATABASE db_library;


CREATE TABLE Library_Branch (
	BranchID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	BranchName VARCHAR(50) NOT NULL,
	Address VARCHAR(80) NOT NULL
);


CREATE TABLE Publisher (
	PublisherName VARCHAR(50) PRIMARY KEY NOT NULL,
	Address VARCHAR(80) NOT NULL,
	Phone VARCHAR(25) NOT NULL,
);


CREATE TABLE Borrower (
	CardNo INT PRIMARY KEY NOT NULL IDENTITY (100,1),
	Name VARCHAR(50) NOT NULL,
	Address VARCHAR(80) NOT NULL,
	Phone VARCHAR(25) NOT NULL
);


CREATE TABLE Books (
	BookID INT PRIMARY KEY NOT NULL IDENTITY (1000,1),
	Title VARCHAR(50) NOT NULL,
	PublisherName VARCHAR(50) NOT NULL CONSTRAINT bk_PublisherName FOREIGN KEY REFERENCES Publisher (PublisherName) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE Book_Authors (
	AuthorsID INT PRIMARY KEY NOT NULL IDENTITY (3000,1),
	BookID INT NOT NULL CONSTRAINT ba_BookID FOREIGN KEY REFERENCES Books (BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	AuthorName VARCHAR(50)
);


CREATE TABLE Book_Copies (
	CopiesID INT PRIMARY KEY NOT NULL IDENTITY (2000,1),
	BookID INT NOT NULL CONSTRAINT bc_BookID FOREIGN KEY REFERENCES Books (BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID INT NOT NULL CONSTRAINT bc_BranchID FOREIGN KEY REFERENCES Library_Branch (BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
	Number_of_Copies INT NOT NULL
);


CREATE TABLE Book_Loans (
	LoansID INT PRIMARY KEY NOT NULL IDENTITY (4000,1),
	BookID INT NOT NULL CONSTRAINT bl_BookID FOREIGN KEY REFERENCES Books (BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchID INT NOT NULL CONSTRAINT bl_BranchID FOREIGN KEY REFERENCES Library_Branch (BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
	CardNo INT NOT NULL CONSTRAINT bl_CardNo FOREIGN KEY REFERENCES Borrower (CardNo) ON UPDATE CASCADE ON DELETE CASCADE,
	DateOut DATE,
	DateDue DATE
);